#ifndef _GUARD_SHADER_FUN_WIDGET_SHADER_SNIPPETS_H_
#define _GUARD_SHADER_FUN_WIDGET_SHADER_SNIPPETS_H_

#include "blaze.h"

enum SF_SHADER_SNIPPET_ID
{
    SF_SHADER_SNIPPET_ID_MANGO,
    SF_SHADER_SNIPPET_ID_RED_PULSE,
    SF_SHADER_SNIPPET_ID_PLOT,
    SF_SHADER_SNIPPET_ID_HSB,
    SF_SHADER_SNIPPET_ID_FLAME,
    SF_SHADER_SNIPPET_ID_BUBBLE,
    SF_SHADER_SNIPPET_ID_PLASMA,
    SF_SHADER_SNIPPET_ID_MANDELBROT,
    SF_SHADER_SNIPPET_ID_PERLIN_NOISE,
    SF_SHADER_SNIPPET_ID_FRACTAL,
    SF_SHADER_SNIPPET_ID_COUNT
};

const char* sf_get_shader_snippet(int32_t id);

#endif // !_GUARD_SHADER_FUN_WIDGET_SHADER_SNIPPETS_H_

